# inspired by https://github.com/topheman/update-homebrew-tap-playground/blob/master/.github/workflows/update-homebrew-tap.yml
name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-homebrew-tap:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # âœ… minimal required for pushing commits

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
      - name: Update Homebrew Formula
        uses: topheman/update-homebrew-tap@v2
        with:
          formula-target-repository: topheman/homebrew-tap
          formula-target-file: Formula/snakepipe.rb
          tar-files: |
            {
              "linuxArm": "https://github.com/topheman/snake-pipe-rust/releases/download/${{ github.ref_name }}/snakepipe-aarch64-unknown-linux-gnu.tar.gz",
              "linuxIntel": "https://github.com/topheman/snake-pipe-rust/releases/download/${{ github.ref_name }}/snakepipe-x86_64-unknown-linux-gnu.tar.gz",
              "macArm": "https://github.com/topheman/snake-pipe-rust/releases/download/${{ github.ref_name }}/snakepipe-aarch64-apple-darwin.tar.gz",
              "macIntel": "https://github.com/topheman/snake-pipe-rust/releases/download/${{ github.ref_name }}/snakepipe-x86_64-apple-darwin.tar.gz"
            }
          metadata: |
            {
              "version": "${{ github.ref_name }}",
              "binaryName": "snakepipe",
              "description": "Snake game based on stdin/stdout in rust",
              "homepage": "https://github.com/topheman/snake-pipe-rust",
              "license": "MIT"
            }
          github-token: ${{ secrets.HOMEBREW_TAP_TOKEN }}